### ISSUE TITLE
Connectors Directory: All the storage examples are incorrect with type=linux instead of storage

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub-connector-maven-plugin#57]
### Problem

In the Connectors Directory, our storage examples seem to have type=linux:

Examples
CLI
```
metricshub HOSTNAME -t linux -c +BrocadeSwitch --snmp v2c --community public
```

**metricshub.yaml**
```yaml
resourceGroups:
  <RESOURCE_GROUP>:
    resources:
      <HOSTNAME-ID>:
        attributes:
          host.name: <HOSTNAME> # Change with actual host name
          host.type: linux
        selectConnectors: [ BrocadeSwitch ] # Optional, to load only this connector
        protocols:
          snmp:
            version: v2c # Read documentation for v1, v2c and v3
            community: public # or probably something more secure
```
