### ISSUE TITLE
Display the new additional connectors configuration

### ISSUE THREAD

**Issue by CherfaElyes** [sentrysoftware/metricshub-connector-maven-plugin#63]
Instead of:
``` yaml
variables:
  connectorId:
    variableName1: variableValue1
    variableName2: variableValue2
```
Replace by: 
``` yaml
additionalConnectors:
  additionalConnectorId: # key: unique identifier for the connector
    uses: connectorId # Optional - Specify the original connector id if this original connector id is not specified in the key
    force: true # Optional - true by default; set to false to allow for staging in auto detection only.
    variables:
      variableName1: variableValue1 # Specify key-value pairs for connector variables
      variableName2: variableValue2
```
In the generated MetricsHub.yaml configuration.
